### ISSUE TITLE
Warning about multiple namespaces

### ISSUE THREAD

**Issue by JulioV** [hzambran/hydroTSM#10]
Hi, In R 3.4.1 for x86_64-w64-mingw32, if I load zoo, hydroTSM, and imputeTS, I got the following warning three times:

``` R
library("zoo")
library("hydroTSM") #izoo2rzoo
library("imputeTS") #na.mean

Found more than one class "zoo" in cache; using the first, from namespace 'quantmod'
Also defined by ‘spacetime’
```

Is this a bug, or is there something I'm not doing correctly?

**Comment by wadhawan2411radhika** [comment]
facing same issue

**Comment by hzambran** [comment]
I apologise for the big delay in my response.

In R 4.3.0, the only message (not warning) I get is:
```

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 

Attaching package: ‘imputeTS’

The following object is masked from ‘package:zoo’:

    na.locf
```

which is not related to `hydroTSM`, but to `imputeTS`
So, this issue is closed.
