### ISSUE TITLE
Wrong DOI in CITATION file

### ISSUE THREAD

**Issue by odelaigue** [hzambran/hydroTSM#12]
Your citation file seems to be wrong.

The DOI seems false at the first occurance.

doi: https://doi.org/10.5281/zenodo.839864

and not: doi: https://doi.org/10.5281/zenodo.83964

**Comment by hzambran** [comment]
Thank you very much for noticing this.

Since the [new version 0.7-0](https://cran.r-project.org/package=hydroTSM), I recommend to use the doi embracing all the versions:

doi:10.5281/zenodo.839565
