### ISSUE TITLE
daily2monthly, hydroplot: error

### ISSUE THREAD

**Issue by wdvichete84** [hzambran/hydroTSM#13]
I've been using the hydroTSM library (congrats!).

Since last week is not working anymore.

After import data, I tried to use dailymonthly, hydroplot, and appear the message:
Error in Summary.factor(c(5L, 542L, 138L, 5L, 598L, 5L, 184L, 5L, 149L,  : 
  ‘sum’ not meaningful for factors

When I try use smry(x):
> smry(x)
              Index  x
Min.     1985-01-01 NA
1st Qu.  1993-09-26 NA
Median   2002-06-21 NA
Mean     2002-06-21 NA
3rd Qu.  2011-03-16 NA
Max.     2019-12-09 NA
IQR            <NA> NA
sd             <NA> NA
cv             <NA> NA
Skewness       <NA> NA
Kurtosis       <NA> NA
NA's           <NA> NA
n              <NA> NA

Any suggestion to fix?

**Comment by hzambran** [comment]
closed due to non-reproducible example?
