### ISSUE TITLE
error with daily2monthly with FUN=sum and nr.rm=T

### ISSUE THREAD

**Issue by nduqueg** [hzambran/hydroTSM#14]
Hi
Thank you for creating this enormusly useful package

I have found a problem when you transform data from daily2monthly or 2annual using the "sum" function and use the na.rm=T.

When one has a daily series and that series has a complete month without values, it should return an NA, doesn´t it? It happens that it returns a 0 as if all the NA in that month were 0.
The same happens when I tried to accummulate values from monthly to annual.

I manage to correct it with this three simple commands:

Sobs.mes <- daily2monthly(Sobs, FUN=sum, na.rm=T)
ind.arr <- which(Sobs.mes == 0, arr.ind = T)
for (i in 1:4) {Sobs.mes[ ind.arr[ which( ind.arr[ ,2] == i ), 1], i] <- NA}

Hope that can be changed for the next update

All the best
Nicolás Duque-Gardeazábal

**Comment by jthurner** [comment]
Set na.rm to FALSE instead – from the documentation:
```
TRUE : the monthly and annual values are computed considering only those values different from NA
FALSE: if there is AT LEAST one NA within a year, the monthly values are NA
``` 
This behavior is identical to how na.rm works in base functions. 

You can supply your own function if you would like to change how missing data is treated. For example, to define a threshold as fraction of missing data above which the aggregated value becomes NA:

```
sum_na_thresh <- function(x, na.rm) {
  na_n <- sum(is.na(x))
  if((na_n > 0) & (na_n / length(x) > na.rm)) {
    return(NA)
  } else {
    return(sum(x, na.rm = TRUE))
  }
}
```
Setting half of the first month in the example data to NA:
```
> data(SanMartinoPPts)
> x <- SanMartinoPPts
> window(x,start="1921-01-01", end="1921-01-15") <- NA

> daily2monthly(x, FUN = sum_na_thresh, na.rm=0.75) %>% head
1921-01-01 1921-02-01 1921-03-01 1921-04-01 1921-05-01 1921-06-01 
      48.0       42.0       19.2       60.9      122.0       87.0 

> daily2monthly(x, FUN = sum_na_thresh, na.rm=0.25) %>% head
1921-01-01 1921-02-01 1921-03-01 1921-04-01 1921-05-01 1921-06-01 
        NA       42.0       19.2       60.9      122.0       87.0 
```
Note that only na.rm is passed to FUN, you can not add your own arguments in the ellipsis.

@hzambran  typo in the description of na.RM=FALSE:

> if there is AT LEAST one NA within a ~~year~~ **month**, the monthly values are NA

**Comment by nduqueg** [comment]
@jthurner great idea to implement a threshold Many thanks
