### ISSUE TITLE
Vulnerability to absence of retiring r-spatial packages

### ISSUE THREAD

**Issue by rsbivand** [hzambran/hydroTSM#19]
[00check.log](https://github.com/hzambran/hydroTSM/files/11139516/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages  on the library path. `hydroTSM` depends strongly on `maptools` to use `maptools::readShapePoly`, which is has been deprecated for years. Both `gstat` and `automap` depend strongly on `sf`, so there is no reason in terms of load image to avoid `sf`. If you wish to stay with `sp` objects, read with `sf` and coerce to `sp`.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
@hzambran See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN. See also https://github.com/hzambran/hydroTSM/issues/21 which duplicates this. If you care to read https://r-spatial.org/r/2023/05/15/evolution4.html or https://r-spatial.org/r/2023/04/10/evolution3.html, you'll see how to resolve the maptools dependency (`as(sf::st_read(), "Spatial")`).

**Comment by rsbivand** [comment]
@hzambran  From hydroTSM_0.6-25.tar.gz, I get: 
[00check.log](https://github.com/hzambran/hydroTSM/files/12266720/00check.log)
with:
```
* checking data for non-ASCII characters ... WARNING
  Error loading dataset 'EbroCatchmentsCHE':
   Error in .requirePackage(package) : unable to find required package 'sp'
  
  Error loading dataset 'EbroDEM1000m':
   Error in .requirePackage(package) : unable to find required package 'sp'
  
  The dataset(s) may use package(s) not declared in Depends/Imports.
```
Adding `sp` to `Suggests:` in `DESCRIPTION`, needed because S4 classes are defined in `sp` gives this check log: [00check.log](https://github.com/hzambran/hydroTSM/files/12266740/00check.log)

**Comment by rsbivand** [comment]
@hzambran Less than three weeks remain to fix this.

**Comment by rsbivand** [comment]
@hzambran R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos.

**Comment by hzambran** [comment]
Dear Roger,

I really apologise for not having addressed this warning before, even with the large time in advance used for launching the warning.

**hydroTSM** is finally back on CRAN: [https://cran.r-project.org/package=hydroTSM](https://cran.r-project.org/package=hydroTSM).

Thank you very much for your messages and patience.
