### ISSUE TITLE
Plans to re-publish to CRAN?

### ISSUE THREAD

**Issue by moritzshore** [hzambran/hydroTSM#23]
Hi,

Thanks for your packages, they are very nice! I was wondering if there were any plans to fix the dependency on the now archived `maptools` and to re-publish to CRAN? Same goes for the `hydroGOF` package (which is actually the package I am more interested in).

I ask mainly because my package depends on `hydroGOF` so it would be nice to know if I should plan installing from GitHub or CRAN long term... (preferably CRAN 😃).

Best, 
Moritz

**Comment by hzambran** [comment]
I'm sorry for now replying before, but it was really impossible.

hydroTSM is back on CRAN now (https://cran.r-project.org/package=hydroTSM) and the same goes for hydroGOF (https://cran.r-project.org/package=hydroGOF).

I really regret any inconvenient these absence from CRAN might have caused to your package.

**Comment by moritzshore** [comment]
No worries, thank you!
