### ISSUE TITLE
Imminent removal from Environmetrics Task View

### ISSUE THREAD

**Issue by gavinsimpson** [hzambran/hydroTSM#24]
As HydroTSM has been archived on CRAN, because of the dependency on maptools (which is now archived following the great upheaval), it now also needs to be removed from the Environmetrics Task View cran-task-views/Environmetrics#15. If you plan to fix the issue and resubmit to CRAN, great, I can hold off removing it from the view. I see that others have raised the specific issue of the maptools dependency over recent months but I haven't seen a response from you. If I don't hear back by Jan 2nd 2024, I'll remove HydroTSM and HydroGOF from the Task View. If you need help getting the package back on CRAN, let us know and I might have time to help.

**Comment by boshek** [comment]
Piggybacking on @gavinsimpson's message here, the same scenario will result with the Hydrology task view. I would also extend the same offer as Gavin if you would like some help.

**Comment by gavinsimpson** [comment]
Closing this as I have removed hydroTSM and hydroGOF from the task view. If you get the packages back on CRAN, let me know and I can revert these changes and get the packages back into the task view.

**Comment by hzambran** [comment]
Dear Gavin and Boshek,

I really apologise for my late reply, but in December we were finishing the spring semester and (unfortunately) I did not check this e-mail.

I was working on a major revision of hydroTSM, hydroGOF and hydroPSO, and just last week I managed to start submitting the new versions to CRAN.

hydroTSM is already on CRAN: [https://cran.r-project.org/package=hydroTSM](https://cran.r-project.org/package=hydroTSM), with several new functions and changes ([https://cran.r-project.org/web/packages/hydroTSM/news/news.html](https://cran.r-project.org/web/packages/hydroTSM/news/news.html))

hydroGOF is being submitted today and should be there on Monday.

I would really appreciate it if you could put those packages back on the Environmetrics and Hydrology Task Viewes at your earlier convenience.

hydroPSO should be there at the end of next week.

Thank you very much for maintaining the Environmetrics and Hydrology Task View

Mauricio

**Comment by boshek** [comment]
Thanks for getting these back on CRAN!

Issue tracked here: https://github.com/cran-task-views/Hydrology/issues/164
