### ISSUE TITLE
fdc

### ISSUE THREAD

**Issue by beareyes** [hzambran/hydroTSM#4]
Estimado Mauricio, primero que todo, felicitaciones por el package, me ha sido muy util para mi trabajo. Lo unico, es que me gustaria saber si hay alguna manera de que la funcion fdc, en vez de solo plotear la flow duration curve, tambien entregue los valores correspondientes. Eso me seria de gran utilidad.

Muchas gracias de antemano, saludos.

**Comment by hzambran** [comment]
Estimado beareyes,

Disculpa lo tardío de mi respuesta, pero estuve fuera de la oficina y con muy poco acesso a Internet.

Si hay una forma de obtener los valores correspondientes a la `fdc` de cada punto:

```
## Loading daily streamflows at the station Oca en Ona (Ebro River basin, Spain) ##
     data(OcaEnOnaQts)
     
     ## Daily Flow Duration Curve
     x <- fdc(OcaEnOnaQts)

     x
```

IHTH
