### ISSUE TITLE
hydroTSM load problem on mac

### ISSUE THREAD

**Issue by fipoucat** [hzambran/hydroTSM#8]
I installed hydroTSM without problem, but getting errors when loading the library:

library(hydroTSM)
Error: package or namespace load failed for ‘hydroTSM’:
 package slot missing from signature for generic ‘coerce’
and classes STFDF, RasterBrick
cannot use with duplicate class names (the package may need to be re-installed)
> 
Urgent help on what to do, highly appreciated

**Comment by fipoucat** [comment]
still facing the same problem.

Help please

**Comment by hzambran** [comment]
If you are still facing the problem, could you send the output of sessionInfo()?

**Comment by fipoucat** [comment]
> library(hydroTSM)
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: xts
Error: package or namespace load failed for ‘hydroTSM’:
 package slot missing from signature for generic ‘coerce’
and classes STFDF, RasterBrick
cannot use with duplicate class names (the package may need to be
re-installed)
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK:
/Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] xts_0.10-1 zoo_1.8-0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13       lattice_0.20-35    class_7.3-14
gtools_3.7.0       lmtest_0.9-35      foreach_1.4.4
 [7] plyr_1.8.4         MatrixModels_0.4-1 e1071_1.6-8
spam_2.1-1         ggplot2_2.2.1      rlang_0.1.4
[13] lazyeval_0.2.1     curl_3.0           minqa_1.2.4
SparseM_1.77       fracdiff_1.4-2     raster_2.6-7
[19] TTR_0.23-2         nloptr_1.0.4       R.utils_2.6.0
R.oo_1.21.0        Matrix_1.2-12      splines_3.4.3
[25] lme4_1.1-14        foreign_0.8-69     stringr_1.2.0
munsell_0.4.3      compiler_3.4.3     forecast_8.2
[31] tcltk_3.4.3        nnet_7.3-12        tibble_1.3.4
intervals_0.15.1   quadprog_1.5-5     codetools_0.2-15
[37] greenbrown_2.4.3   MASS_7.3-47        R.methodsS3_1.7.1
grid_3.4.3         nlme_3.1-131       gtable_0.2.0
[43] magrittr_1.5       scales_0.5.0       ncdf4_1.16
quantmod_0.4-11    stringi_1.1.6      tseries_0.10-42
[49] doParallel_1.0.11  sp_1.2-5           strucchange_1.5-2
timeDate_3042.101  boot_1.3-20        sandwich_2.4-0
[55] RColorBrewer_1.1-2 iterators_1.0.8    tools_3.4.3
phenopix_2.3.1     maps_3.2.0         fields_9.0
[61] jpeg_0.1-8         yaml_2.1.14        bcp_4.0.0
bfast_1.5.7        parallel_3.4.3     colorspace_1.3-2
[67] maptools_0.9-2     SDMTools_1.1-221   Kendall_2.2
dotCall64_0.9-04   quantreg_5.34

**Comment by fipoucat** [comment]
Dear Mauricion,

Still problems installing hydroTSM, error below:

> library(hydroTSM)
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: xts
Error: package or namespace load failed for ‘hydroTSM’:
 package slot missing from signature for generic ‘coerce’
and classes STFDF, RasterBrick
cannot use with duplicate class names (the package may need to be
re-installed)

Abdoulaye

**Comment by hzambran** [comment]
Dear 
I apologise for my very late reply, but it was impossible to answer before.

I'm using `hydroTSM_0.5-1` wihtout any probelm both in GNU/Linux and MacOSX, using `xts_0.10-0`  and   `zoo_1.8-1 `.

Could you tell me the versions of `zoo`, `xts`, and `hydroTSM` you are trying to install?

**Comment by fipoucat** [comment]
I am using
zoo 1.8.1
xts 0.10.1
hydroTSM 0.5-1

Abdoulaye

**Comment by hzambran** [comment]
Problem solved on Mac OS Monterey, Ventura, Sonoma.
