### ISSUE TITLE
HydroTSM and R 3.5

### ISSUE THREAD

**Issue by ericbardou** [hzambran/hydroTSM#9]
Hi,
I have difficulty in using HydroTSM on R 3.5 (I run code working before and receive many error, perharps also on zoo package). Do you know if there is some difficulties in this perspective ?
Best Regards

**Comment by hzambran** [comment]
The latest stable R version is 3.4.3. I'm not aware about R 3.5 on the R-devel branch of development.

Could you send the output of `sessionInfo()` ?

**Comment by ericbardou** [comment]
Thanks

I reinstall version 3.4.3 as I have to many bug

Eric

 

De : Mauricio Zambrano-Bigiarini <notifications@github.com> 
Envoyé : lundi, 5 mars 2018 21:55
À : hzambran/hydroTSM <hydroTSM@noreply.github.com>
Cc : ericbardou <eric.bardou@bluewin.ch>; Author <author@noreply.github.com>
Objet : Re: [hzambran/hydroTSM] HydroTSM and R 3.5 (#9)

 

The latest stable R version is 3.4.3. I'm not aware about R 3.5 on the R-devel branch of development.

Could you send the output of sessionInfo() ?

**Comment by tungmilan** [comment]
hydroTSM works fine for me on Windows 10 + `R 3.5.0`

**Comment by hzambran** [comment]
Thanks for confirming that.

I'm not using R 3.5.0 yet...



=====================================
Department of Civil Engineering
Faculty of Engineering and Science
Universidad de La Frontera, Temuco, Chile
=====================================
"If you want to go fast, go alone. If you want
to  go far, go together" (African proverb)
=====================================
Linux user #454569 -- Linux Mint user
